### ISSUE TITLE
is this package published on pip?

### ISSUE THREAD

**Issue by cosimoNigro** [open-gamma-ray-astro/ogadf-schema#1]
Hi,

is this package available on the python package index?
I wanted to use it as a dependency into another code but I cannot find it via pip.

I tried
```bash
pip install ogadf-schema
```
and
```bash
pip search ogadf
```
with no success.

Thanks

**Comment by MaxNoe** [comment]
I have not published it yet, no.

**Comment by MaxNoe** [comment]
I don't think this is ready yet (not exactly compliant to the 0.2 version of the standard, more to the current master), but I can upload it to pypi so you can try it out.

**Comment by MaxNoe** [comment]
For now, you can use dependency links like this:

```
ogadf-schema @ https://github.com/open-gamma-ray-astro/ogadf-schema/archive/master.tar.gz
```

**Comment by cosimoNigro** [comment]
Ok, I specified the requirement as you suggested.
You can close the issue (or close it when you publish, as a reminder)

Thank you

**Comment by MaxNoe** [comment]
This is now on pypi
